name: "Tyler's World"
favicon: null
layout_spectrum: 0.90215
typography_spectrum: 0.22903
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "Tyler's World"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e240b'
    - '#febae9'
    - '#eb9c3f'
    - '#eaf0fc'
    - '#7eae58'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
