name: "Tyler's World"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.80338
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: "Tyler's World"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#163f77'
    - '#2d81d2'
    - '#e6f6f8'
    - '#42bcf7'
    - '#a0d5dc'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
